import Head from 'next/head'
// import Menu from './Menu'
// import styles from '../../styles/layout.module.css'
import Nav from '../Navbar/Nav'
import { Grid } from '@nextui-org/react'

const Layout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title> RASIL {title ? `| ${title}` : ''}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      {/* esto "⬇" va en Index para que solo se renderize en la home */}

      <Grid.Container css={{ overflow: 'hidden' }}>
        {children}
      </Grid.Container>
      {/* <Container css={{ pt: '76px', userSelect: 'none' }}>{children} </Container> */}
    </>
  )
}

export default Layout
